# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-tui" do
  name "aws-tui"
  desc "Terminal User Interface for AWS services"
  homepage "https://github.com/aws-tui/aws-tui"
  version "0.1.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-tui"

  on_macos do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-amd64.tar.gz"
      sha256 "fe42dd81382be03a15f231ee176ce64e58943060ca347deda577b20d66524f81"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-arm64.tar.gz"
      sha256 "63026e645817b1d9ea866782151b02b658eff4698d2226984402589c80a18715"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-amd64.tar.gz"
      sha256 "b74545168639035b93f983d5df0f38f71d218c147eca58a3592a989d283713ea"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-arm64.tar.gz"
      sha256 "d30400e737fcc1b87f7a4d152dfd2151b6d699224356e7f9f43e087249344241"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-tui"]
    end
  end

  # No zap stanza required
end
