# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-tui" do
  name "aws-tui"
  desc "Terminal User Interface for AWS services"
  homepage "https://github.com/aws-tui/aws-tui"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-tui"

  on_macos do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-amd64.tar.gz"
      sha256 "738383be659f3b302bf705d8f9ab9fd301a85d7200affdc8d9d41e923fca89eb"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-arm64.tar.gz"
      sha256 "92f6773e1039af458957fd18b870fc407fbf50daaa4803533b3a3fe80907db6c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-amd64.tar.gz"
      sha256 "f1a7c0aabb6e4c74a585f5a26cf2ddf42da8b98b637ccb5f482a632179a68feb"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-arm64.tar.gz"
      sha256 "0d0f16f63fdb71c2c1e8e2c69fcd656007665b4d801919453b99f0665eb0eb5c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-tui"]
    end
  end

  # No zap stanza required
end
