# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-tui" do
  name "aws-tui"
  desc "Terminal User Interface for AWS services"
  homepage "https://github.com/aws-tui/aws-tui"
  version "0.1.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-tui"

  on_macos do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-amd64.tar.gz"
      sha256 "f0cd46ee1e4273e831b8627851dd72072d5f8663c76b9c3267c6eeba86e11c6a"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-arm64.tar.gz"
      sha256 "5b310390da3a4b4b9fbd508ec81cc25c654088d86924e841bfef497f5dadb1ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-amd64.tar.gz"
      sha256 "780cf53a250fb36739a0f2a8e005238d1e337236955d12886cc7472f4df1eae2"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-arm64.tar.gz"
      sha256 "04bcd2b68b23736b6e33f72b7305c8f705a10d236591e2fbcd0deca66a8f7628"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-tui"]
    end
  end

  # No zap stanza required
end
