# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-tui" do
  name "aws-tui"
  desc "Terminal User Interface for AWS services"
  homepage "https://github.com/aws-tui/aws-tui"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-tui"

  on_macos do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-amd64.tar.gz"
      sha256 "74eba5e6ebbf29e0c407408d98e41351b5d6d14279248da3e16b313a7cd5945d"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-darwin-arm64.tar.gz"
      sha256 "b466272ac40d50a023488494ffbd0ccbbd64b0dee3d0c7412c673782159ac933"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-amd64.tar.gz"
      sha256 "1c0fde6565e3f86b76291d4c0b6b0404da32c32935f25ee3a03efcbb5a0137b0"
    end
    on_arm do
      url "https://github.com/aws-tui/aws-tui/releases/download/v#{version}/aws-tui-linux-arm64.tar.gz"
      sha256 "1a6840bb698dddee31c8cb46afb75957d9775f4fce4a7b992a291cb086aeddf4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-tui"]
    end
  end

  # No zap stanza required
end
