# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsTui < Formula
  desc "Terminal User Interface for AWS services"
  homepage "https://github.com/aws-tui/aws-tui"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aws-tui/aws-tui/releases/download/v0.1.7/aws-tui-darwin-amd64.tar.gz"
      sha256 "501678b521a5dcc86407d28547ed9d4ec8bf73b4447921b1040dfe64e908a841"

      def install
        bin.install "aws-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aws-tui/aws-tui/releases/download/v0.1.7/aws-tui-darwin-arm64.tar.gz"
      sha256 "2c4a6f92a5fa059288bd3eaed2362427449eb6b15ebd06645c64a5257482eb99"

      def install
        bin.install "aws-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aws-tui/aws-tui/releases/download/v0.1.7/aws-tui-linux-amd64.tar.gz"
      sha256 "021f4ceeea6dbb13202155acc1d669efd622aa737b2ccb8c7a2c60bf94e52469"
      def install
        bin.install "aws-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aws-tui/aws-tui/releases/download/v0.1.7/aws-tui-linux-arm64.tar.gz"
      sha256 "a0bc27f0b7211398a1a21c7c4836c4f888cb28b7ed038bd77d50be62f2d0b5d3"
      def install
        bin.install "aws-tui"
      end
    end
  end

  test do
    assert_match "aws-tui", shell_output("#{bin}/aws-tui --version", 2)
  end
end
